# Generated by Django 5.0.14 on 2026-08-05 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_step', models.CharField(choices=[('welcome', 'Welcome'), ('demographics', 'Demographics'), ('conditions', 'Conditions'), ('lifestyle', 'Lifestyle'), ('family', 'Family History'), ('summary', 'Summary'), ('complete', 'Complete')], default='welcome', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Disease-conditional fields and preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profile',
            },
        ),
    ]
