# Generated by Django 5.0.4 on 2026-04-09 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=32)),
                ('ethnicity', models.JSONField(blank=True, default=list)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=3)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_long', models.FloatField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('insurance_status', models.CharField(blank=True, default='', max_length=64)),
                ('employment_status', models.CharField(blank=True, default='', max_length=64)),
                ('disease', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('completeness_score', models.FloatField(default=0.0)),
                ('completeness_by_category', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profile_patientinfo',
            },
        ),
        migrations.CreateModel(
            name='PatientInfoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_fields', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('fhir', 'FHIR sync'), ('document_extraction', 'Document AI extraction'), ('caregiver', 'Caregiver edit')], default='manual', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='patient_profile.patientinfo')),
            ],
            options={
                'db_table': 'patient_profile_patientinfoversion',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient_info', '-timestamp'], name='patient_pro_patient_01f50a_idx')],
            },
        ),
    ]
