# Generated by Django 5.0.4 on 2026-04-15 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'lab categories',
                'db_table': 'labs_labcategory',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('loinc_code', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('default_unit', models.CharField(max_length=32)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('reference_ranges', models.JSONField(blank=True, default=dict)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('qualitative', 'Qualitative'), ('ratio', 'Ratio')], default='numeric', max_length=16)),
                ('molecular_weight', models.FloatField(blank=True, help_text='Molecular weight in g/mol, for molar↔mass conversions (§8.2).', null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='labs.labcategory')),
            ],
            options={
                'db_table': 'labs_labtesttype',
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_qualitative', models.CharField(blank=True, default='', max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('source_text', models.CharField(max_length=64)),
                ('source_unit', models.CharField(max_length=32)),
                ('reference_min', models.FloatField(blank=True, null=True)),
                ('reference_max', models.FloatField(blank=True, null=True)),
                ('reference_source', models.CharField(choices=[('report', 'From report'), ('catalog', 'Catalog default'), ('none', 'No range')], default='none', max_length=8)),
                ('match_method', models.CharField(choices=[('loinc', 'LOINC direct'), ('exact_alias', 'Exact alias match'), ('fuzzy', 'Fuzzy match'), ('disambiguation', 'Disambiguation rule'), ('manual', 'Patient manually matched'), ('unmatched', 'Unmatched')], default='manual', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('document_extraction', 'Document extraction'), ('fhir', 'FHIR sync')], default='manual', max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('in_range', 'In range'), ('below', 'Below'), ('above', 'Above'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('measured_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='labs.labtesttype')),
            ],
            options={
                'db_table': 'labs_labresult',
                'ordering': ['-measured_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='labtesttype',
            index=models.Index(fields=['loinc_code'], name='labs_labtes_loinc_c_9ff2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['user', 'test_type', '-measured_at'], name='labs_labres_user_id_528051_idx'),
        ),
    ]
