# Generated by Django 5.0.4 on 2026-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttype',
            name='alternative_units',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
