# Generated by Django 5.0.4 on 2026-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_labtesttype_alternative_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttype',
            name='sample_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
