# Generated by Django 5.0.4 on 2026-04-20 12:38

import apps.labs.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_labtesttype_sample_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='upload_id',
        ),
        migrations.CreateModel(
            name='LabUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('lab_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('parsed_results', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'labs_labupload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='labs.labupload'),
        ),
        migrations.CreateModel(
            name='LabUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.labs.models._lab_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('file_order', models.PositiveSmallIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='labs.labupload')),
            ],
            options={
                'db_table': 'labs_labuploadfile',
                'ordering': ['upload_id', 'file_order'],
            },
        ),
        migrations.AddIndex(
            model_name='labupload',
            index=models.Index(fields=['user', '-created_at'], name='labs_labupl_user_id_8c3214_idx'),
        ),
        migrations.AddIndex(
            model_name='labuploadfile',
            index=models.Index(fields=['sha256'], name='labs_labupl_sha256_5f8828_idx'),
        ),
    ]
