# Generated by Django 5.0.4 on 2026-04-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_remove_labresult_upload_id_labupload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtesttype',
            name='aliases',
        ),
        migrations.AddField(
            model_name='labtesttype',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, default='', help_text='NFKD + casefold + punctuation strip of `name`. Used by matching.resolve_test_identity to group no-LOINC rows. Populated in save().', max_length=128),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='match_method',
            field=models.CharField(choices=[('loinc', 'LOINC direct'), ('name_fallback', 'Name fallback (no LOINC)'), ('manual', 'Patient manually matched'), ('unmatched', 'Unmatched'), ('exact_alias', 'Exact alias match (legacy)'), ('fuzzy', 'Fuzzy match (legacy)'), ('disambiguation', 'Disambiguation rule (legacy)')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='labtesttype',
            name='abbreviation',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='labtesttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='labs.labcategory'),
        ),
        migrations.AddIndex(
            model_name='labtesttype',
            index=models.Index(fields=['name_normalized'], name='labs_labtes_name_no_939f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='labtesttype',
            constraint=models.UniqueConstraint(condition=models.Q(('loinc_code__gt', '')), fields=('loinc_code',), name='uniq_labs_labtesttype_loinc_code_when_set'),
        ),
    ]
