# Generated by Django 5.0.4 on 2026-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_v2_rename_and_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='raw_llm_response',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
