# Generated by Django 5.0.4 on 2026-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_add_raw_llm_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='labvalue',
            name='reference_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
