# Generated by Django 4.2.30 on 2026-05-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_add_reference_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
